using System;
using System.Linq;
using CodeBrix.Develop.UI.Generator.Model;

namespace CodeBrix.Develop.UI.Generator.Renderer.Public; //was previously: Generator.Renderer.Public;

internal static class InterfaceImplementationFunctions
{
    public static string Render(GirModel.Interface @interface)
    {
        return $@"
using System;
using System.Linq;
using CodeBrix.Develop.UI.GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(@interface.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class {Model.Interface.GetImplementationName(@interface)} : GObject.GTypeProvider
{{
    {FunctionRenderer.Render(@interface.TypeFunction)}

    {@interface.Functions
        .Select(FunctionRenderer.Render)
        .Join(Environment.NewLine)}
}}";
    }
}
