using System;
using System.Linq;
using System.Text;
using CodeBrix.Develop.UI.Generator.Model;

namespace CodeBrix.Develop.UI.Generator.Renderer.Public; //was previously: Generator.Renderer.Public;

public static partial class ClassProperties
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using CodeBrix.Develop.UI.GObject;
using System.Runtime.InteropServices;
#nullable enable
namespace {Namespace.GetPublicName(cls.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class {cls.Name}
    {{
        {cls.Properties
            .Where(Property.IsEnabled)
            .Select(prop => Render(cls, prop))
            .Join(Environment.NewLine)}
    }}
}}";
    }

    private static string Render(GirModel.Class cls, GirModel.Property property)
    {
        try
        {
            Property.ThrowIfNotSupported(cls, property);

            var builder = new StringBuilder();
            builder.AppendLine(RenderDescriptor(cls, property));
            builder.AppendLine(RenderAccessor(cls, property));

            return builder.ToString();
        }
        catch (Exception ex)
        {
            var message = $"Did not generate property '{cls.Name}.{property.Name}': {ex.Message}";

            if (ex is NotImplementedException)
                Log.Debug(message);
            else
                Log.Warning(message);

            return string.Empty;
        }
    }
}
