using System;
using System.Collections.Generic;
using System.IO;

namespace CodeBrix.Develop.UI.Generator.Generator; //was previously: Generator.Generator;

internal class Publisher
{
    // Prepended to every generated file. The <auto-generated/> marker makes
    // analyzers treat the file as generated code, and the blanket pragma
    // keeps compiler warnings in generated code (which cannot be fixed by
    // hand) from failing the family's zero-warnings builds. Hand-written
    // source files are unaffected.
    private const string GeneratedFileHeader = "// <auto-generated/>\n#pragma warning disable\n\n";

    private string TargetFolder { get; set; }

    public Publisher(string targetFolder)
    {
        TargetFolder = targetFolder;
    }

    public void Publish(CodeUnit codeUnit)
    {
        var projectFolder = Configuration.ProjectFolderNameMapper?.Invoke(codeUnit.Project) ?? codeUnit.Project;

        var allFolders = new List<string>
        {
            TargetFolder,
            projectFolder,
            codeUnit.IsInternal ? "Internal" : "Public",
            GetFileName(codeUnit)
        };

        var path = Path.Combine(allFolders.ToArray());
        var directoryName = Path.GetDirectoryName(path);

        if (directoryName is null)
            throw new Exception("Can not get directory for path: " + path);

        Directory.CreateDirectory(directoryName);
        File.WriteAllText(path, GeneratedFileHeader + codeUnit.Source);
    }

    private static string GetFileName(CodeUnit codeUnit) => codeUnit.Name + ".Generated.cs";
}
