using System;
using System.Linq;
using CodeBrix.Develop.UI.Generator.Model;

namespace CodeBrix.Develop.UI.Generator.Renderer.Public; //was previously: Generator.Renderer.Public;

internal static class ClassCallbacks
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using System.Linq;
using CodeBrix.Develop.UI.GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(cls.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class {cls.Name}
{{
    {cls.Callbacks
        .Select(Callback.Render)
        .Join(Environment.NewLine)}
}}";
    }
}
