using CodeBrix.Develop.UI.Generator.Model;

namespace CodeBrix.Develop.UI.Generator.Renderer.Public; //was previously: Generator.Renderer.Public;

internal static class FundamentalClassFramework
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using CodeBrix.Develop.UI.GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetPublicName(cls.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(cls as GirModel.PlatformDependent)}
public partial class {cls.Name} {RenderInheritance(cls)}
{{
    public {cls.Name}(IntPtr handle) : base(handle) {{ }}
}}";
    }

    private static string RenderInheritance(GirModel.Class cls)
    {
        return cls.Parent is null
            ? $": Fundamental"
            : $": {ComplexType.GetFullyQualified(cls.Parent)}";
    }
}
