<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CodeBrix.Develop.UI.Graphene</AssemblyName>
    <RootNamespace>CodeBrix.Develop.UI.Graphene</RootNamespace>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeBrix.Develop.UI.GObject\CodeBrix.Develop.UI.GObject.csproj" />
  </ItemGroup>

</Project>
