using System;
using System.Linq;
using CodeBrix.Develop.UI.Generator.Model;

namespace CodeBrix.Develop.UI.Generator.Renderer.Internal; //was previously: Generator.Renderer.Internal;

internal static class ClassCallbacks
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using CodeBrix.Develop.UI.GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(cls.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(cls as GirModel.PlatformDependent)}
public partial class {cls.Name}
{{
    {cls.Callbacks.Select(CallbackDelegate.Render).Join(Environment.NewLine)}
    {cls.Callbacks.Select(CallbackCallHandler.Render).Join(Environment.NewLine)}
    {cls.Callbacks.Select(CallbackAsyncHandler.Render).Join(Environment.NewLine)}
    {cls.Callbacks.Select(CallbackForeverHandler.Render).Join(Environment.NewLine)}
    {cls.Callbacks.Select(CallbackNotifiedHandler.Render).Join(Environment.NewLine)}
}}";
    }
}
