using CodeBrix.Develop.UI.Generator.Model;

namespace CodeBrix.Develop.UI.Generator.Renderer.Internal; //was previously: Generator.Renderer.Internal;

internal static class ForeignTypedRecord
{
    public static string Render(GirModel.Record record)
    {
        return $@"
using System;
using CodeBrix.Develop.UI.GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(record.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(record as GirModel.PlatformDependent)}
public partial class {record.Name}
{{
    {Functions.Render(record.TypeFunction)}
}}";
    }
}
