using System.Collections.Generic;
using System.Linq;
using CodeBrix.Develop.UI.Generator.Model;

namespace CodeBrix.Develop.UI.Generator.Renderer.Internal; //was previously: Generator.Renderer.Internal;

internal static class GlobalFunctions
{
    public static string Render(IEnumerable<GirModel.Function> functions)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(functions.First().Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

public static partial class Functions
{{
    {Functions.Render(functions)}
}}";
    }
}
