using CodeBrix.Develop.UI.Generator.Model;

namespace CodeBrix.Develop.UI.Generator.Renderer.Internal; //was previously: Generator.Renderer.Internal;

internal static class InterfaceMethods
{
    public static string Render(GirModel.Interface iface)
    {
        return $@"
using System;
using CodeBrix.Develop.UI.GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(iface.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(iface as GirModel.PlatformDependent)}
public partial class {iface.Name}
{{
    {Functions.Render(iface.TypeFunction)}
    {Functions.Render(iface.Functions)}
    {Methods.Render(iface.Methods)}
}}";
    }
}
