using System;
using System.Linq;
using CodeBrix.Develop.UI.Generator.Model;

namespace CodeBrix.Develop.UI.Generator.Renderer.Internal; //was previously: Generator.Renderer.Internal;

internal static class UntypedRecordData
{
    public static string Render(GirModel.Record record)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(record.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(record as GirModel.PlatformDependent)}
[StructLayout(LayoutKind.Sequential)]
public partial struct {Model.TypedRecord.GetDataName(record)}
{{
    {record.Fields
        .Select(x => x.AnyTypeOrCallback)
        .Where(x => x.IsT1)
        .Select(x => x.AsT1)
        .Select(Callback.Render)
        .Join(Environment.NewLine)}

    {Fields.Render(record.Fields)}
}}";
    }
}
